# Análise de dados AirBnB - Rio de Janeiro

Origem dos dados: http://insideairbnb.com/get-the-data <br>
Dicionário: https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit#gid=1322284596

In [12]:
# Importar as bibliotecas.

In [11]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
#warnings.filterwarnings("ignore")
%matplotlib inline

# Os arquivos base estão na pasta "/datasets/raw/"
import os
for dirname, _, filenames in os.walk('datasets\\raw'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

datasets\raw\calendar.csv.gz
datasets\raw\listings.csv
datasets\raw\listings.csv.gz
datasets\raw\neighbourhoods.csv
datasets\raw\neighbourhoods.geojson
datasets\raw\reviews.csv
datasets\raw\reviews.csv.gz

# Conteúdo de cada tabela

*@@@ Podemos falar um pouco sobre a origem das planilhas, contextualizar a existência de um site da própria empresa com essas informações, separadas por algumas classificações*

|Arquivo   |Data do dataset   |Descrição original | Descrição  |   |
|---|---|---|---|---|
| calendar.csv.gz  | 20 de junho de 2022  | *Detailed Calendar data*  | Base de dados com informações detalhadas de XXX / XXX   |   |
| listings.csv.gz  | 20 de junho de 2022  | *Detailed Listings data*  | Base de dados com informações detalhadas de XXX / XXX     |   |
| reviews.csv.gz  | 20 de junho de 2022  | *Detailed Review data* | Base de dados com informações detalhadas de XXX / XXX     |
| listings.csv | 20 de junho de 2022  | *Summary information and metrics for<br> listings in Rio de Janeiro (good for<br> visualisations).*  | Base de dados sumarizada de XXX / XXX  |   |
| reviews.csv  | 20 de junho de 2022  |  *Summary Review data and Listing ID <br>(to facilitate time based analytics and <br>visualisations linked to a listing).* | Base de dados sumarizada de XXX / XXX  |   |
| neighbourhoods.csv | Sem informação  | *Neighbourhood list for geo filter. <br>Sourced from city or open source GIS files.*  | Base de dados sumarizada de XXX / XXX  |   |
| neighbourhoods.geojson | Sem informação  | *GeoJSON file of neighbourhoods of the city.*  | Base de dados sumarizada de XXX / XXX  |   |

*"Entendemos que a empresa disponibiliza arquivos mais detalhados, com XXX informações, sobre XXX assunto e com os campos XXX, XXX, XXX, ..., XXX mais importantes. 
@@@ Da pra escrever um pouco mais sobre o que podemos encontrar, o que temos de dúvidas, a primeira parte do trabalho"*

In [21]:
# Após listar os arquivos, utilizando pandas, 
# setaremos os dataframes que serão utilizados na análise, 
# tendo como origem as tabelas baixadas
calendario = pd.read_csv("datasets/raw/calendar.csv.gz")
reservas = pd.read_csv("datasets/raw/listings.csv.gz")
reviews = pd.read_csv("datasets/raw/reviews.csv.gz")
resumo_reservas = pd.read_csv("datasets/raw/listings.csv")
resumo_reviews = pd.read_csv("datasets/raw/reviews.csv")
geoloc = pd.read_csv("datasets/raw/neighbourhoods.csv")

## calendario

In [22]:
# .head() mostra as primeiras linhas do arquivo, ajudando a mapear as informações que temos
calendario.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,28053241,2022-06-21,t,"$1,850.00","$1,850.00",2,1125
1,1174007,2022-06-21,t,$107.00,$107.00,2,30
2,1174007,2022-06-22,t,$107.00,$107.00,2,30
3,1174007,2022-06-23,t,$107.00,$107.00,2,30
4,1174007,2022-06-24,t,$107.00,$107.00,2,30

## reservas

In [24]:
reservas.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,15965441,https://www.airbnb.com/rooms/15965441,20220620202144,2022-06-20,Quarto de casal com vista para a Baía de Guana...,"Meu espaço é bom para casais, aventuras indivi...",NaN,https://a0.muscache.com/pictures/76550464-7859...,103691209,https://www.airbnb.com/users/show/103691209,...,NaN,NaN,NaN,NaN,f,3,0,3,0,NaN
1,47908784,https://www.airbnb.com/rooms/47908784,20220620202144,2022-06-20,"Apartamento bem localizado, bonito e familiar!",NaN,NaN,https://a0.muscache.com/pictures/f44537ff-72f1...,83985216,https://www.airbnb.com/users/show/83985216,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,52239613,https://www.airbnb.com/rooms/52239613,20220620202144,2022-06-20,Apartamento com varanda e linda vista,"Condomínio com porteiro 24 horas , piscina, sa...",O condomínio fica em frente ao portão 2 do PRO...,https://a0.muscache.com/pictures/miso/Hosting-...,422870631,https://www.airbnb.com/users/show/422870631,...,4.78,4.78,4.89,NaN,f,1,1,0,0,1.16
3,10445855,https://www.airbnb.com/rooms/10445855,20220620202144,2022-06-20,"Campo dos Afonsos, Sulacap",Casa com vista para as instalações do Parque ...,"Bairro suburbano, tranquilo, seguro, casas bem...",https://a0.muscache.com/pictures/0f42e026-0955...,1647571,https://www.airbnb.com/users/show/1647571,...,4.87,4.70,4.57,NaN,f,1,1,0,0,0.64
4,565405043878669885,https://www.airbnb.com/rooms/565405043878669885,20220620202144,2022-06-20,Pousada completa: 2 quartos com muita natureza!,Este lugar único e cheio de estilo é o cenário...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,24596747,https://www.airbnb.com/users/show/24596747,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN

# reviews

In [25]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,1174007,8837512,2013-11-20,9438993,Chloe,Definitely worth the walk up the hill to get t...
1,556930647599893392,565830572071983778,2022-02-19,68918783,Samila,Uma experiência incrível é única! <br/>Andréia...
2,1174007,9452466,2013-12-29,7418078,Julien,Thiago and his family were the best hosts ever...
3,1174007,9806285,2014-01-11,3738399,Jazmin,Muy lindo el hostel. La vista es excelente y l...
4,1174007,9986412,2014-01-23,124357,Valeria,Really Neat and Clean. Great Place with amazin...

## resumo_reservas

In [26]:
resumo_reservas.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,17878,"Very Nice 2Br in Copacabana w. balcony, fast WiFi",68997,Matthias,NaN,Copacabana,-22.96599,-43.17940,Entire home/apt,350,5,272,2022-04-23,1.87,1,311,8,NaN
1,556930647599893392,Venha passar uma pernoite em um veleiro na Urca!,198206849,Andréia,NaN,Urca,-22.94781,-43.16351,Private room,280,1,1,2022-02-19,0.25,1,365,1,NaN
2,1174007,100% Best View In Copa In Suite 2,3962758,Thiago Luiz,NaN,Copacabana,-22.97277,-43.17966,Private room,107,2,177,2022-06-07,1.69,6,357,29,NaN
3,8410797,Ipanema(Arpoador) 100mdo Mar/ Jan & Carnaval +Fev,42038091,Sheila,NaN,Ipanema,-22.98871,-43.19334,Private room,1000,3,1,2017-09-28,0.02,3,362,0,NaN
4,28053241,Navegar a Bordo de um Veleiro Francês no Rio!,193860988,Luciano,NaN,Urca,-22.95056,-43.17175,Private room,1850,2,0,NaN,NaN,1,180,0,NaN